### ISSUE TITLE
第一次启动会报错

### ISSUE THREAD

**Issue by luw2007** [moenayuki/leanote-dockerfile#2]
第一次启动会有报错. leanote : Text file busy

这个应该是leanote 的问题. 
等我搞定evernote 数据导入 leanote 在解决吧.

**Comment by swjsj** [comment]
之前1.0b2版本能正常用， 现在完全启动不起来了， 不知道什么问题

**Comment by nykma** [comment]
抽空完全重写了，应该可以用了。
